// S&P 500 components with GICS sector classification
export const SP500_STOCKS = [
  // Technology
  { ticker: 'AAPL', name: 'Apple Inc.', sector: 'Technology', subsector: 'Technology Hardware' },
  { ticker: 'MSFT', name: 'Microsoft Corp.', sector: 'Technology', subsector: 'Software' },
  { ticker: 'NVDA', name: 'NVIDIA Corp.', sector: 'Technology', subsector: 'Semiconductors' },
  { ticker: 'AVGO', name: 'Broadcom Inc.', sector: 'Technology', subsector: 'Semiconductors' },
  { ticker: 'ORCL', name: 'Oracle Corp.', sector: 'Technology', subsector: 'Software' },
  { ticker: 'CRM', name: 'Salesforce Inc.', sector: 'Technology', subsector: 'Software' },
  { ticker: 'ACN', name: 'Accenture PLC', sector: 'Technology', subsector: 'IT Services' },
  { ticker: 'AMD', name: 'Advanced Micro Devices', sector: 'Technology', subsector: 'Semiconductors' },
  { ticker: 'QCOM', name: 'Qualcomm Inc.', sector: 'Technology', subsector: 'Semiconductors' },
  { ticker: 'TXN', name: 'Texas Instruments', sector: 'Technology', subsector: 'Semiconductors' },
  { ticker: 'INTC', name: 'Intel Corp.', sector: 'Technology', subsector: 'Semiconductors' },
  { ticker: 'ADBE', name: 'Adobe Inc.', sector: 'Technology', subsector: 'Software' },
  { ticker: 'NOW', name: 'ServiceNow Inc.', sector: 'Technology', subsector: 'Software' },
  { ticker: 'IBM', name: 'IBM Corp.', sector: 'Technology', subsector: 'IT Services' },
  { ticker: 'AMAT', name: 'Applied Materials', sector: 'Technology', subsector: 'Semiconductor Equipment' },
  { ticker: 'MU', name: 'Micron Technology', sector: 'Technology', subsector: 'Semiconductors' },
  { ticker: 'LRCX', name: 'Lam Research', sector: 'Technology', subsector: 'Semiconductor Equipment' },
  { ticker: 'KLAC', name: 'KLA Corp.', sector: 'Technology', subsector: 'Semiconductor Equipment' },
  { ticker: 'SNPS', name: 'Synopsys Inc.', sector: 'Technology', subsector: 'Software' },
  { ticker: 'CDNS', name: 'Cadence Design Systems', sector: 'Technology', subsector: 'Software' },
  { ticker: 'CSCO', name: 'Cisco Systems', sector: 'Technology', subsector: 'Communications Equipment' },
  { ticker: 'ANET', name: 'Arista Networks', sector: 'Technology', subsector: 'Communications Equipment' },
  { ticker: 'PANW', name: 'Palo Alto Networks', sector: 'Technology', subsector: 'Software' },
  { ticker: 'FTNT', name: 'Fortinet Inc.', sector: 'Technology', subsector: 'Software' },
  { ticker: 'HPQ', name: 'HP Inc.', sector: 'Technology', subsector: 'Technology Hardware' },
  { ticker: 'HPE', name: 'Hewlett Packard Enterprise', sector: 'Technology', subsector: 'IT Services' },
  { ticker: 'DELL', name: 'Dell Technologies', sector: 'Technology', subsector: 'Technology Hardware' },
  { ticker: 'STX', name: 'Seagate Technology', sector: 'Technology', subsector: 'Technology Hardware' },
  { ticker: 'WDC', name: 'Western Digital', sector: 'Technology', subsector: 'Technology Hardware' },
  { ticker: 'CTSH', name: 'Cognizant Technology', sector: 'Technology', subsector: 'IT Services' },
  { ticker: 'IT', name: 'Gartner Inc.', sector: 'Technology', subsector: 'IT Services' },
  { ticker: 'CDRE', name: 'Cadre Holdings', sector: 'Technology', subsector: 'Electronic Equipment' },
  { ticker: 'TDY', name: 'Teledyne Technologies', sector: 'Technology', subsector: 'Electronic Equipment' },
  { ticker: 'KEYS', name: 'Keysight Technologies', sector: 'Technology', subsector: 'Electronic Equipment' },
  { ticker: 'MPWR', name: 'Monolithic Power Systems', sector: 'Technology', subsector: 'Semiconductors' },
  { ticker: 'MCHP', name: 'Microchip Technology', sector: 'Technology', subsector: 'Semiconductors' },
  { ticker: 'ON', name: 'ON Semiconductor', sector: 'Technology', subsector: 'Semiconductors' },
  { ticker: 'SWKS', name: 'Skyworks Solutions', sector: 'Technology', subsector: 'Semiconductors' },
  { ticker: 'QRVO', name: 'Qorvo Inc.', sector: 'Technology', subsector: 'Semiconductors' },
  { ticker: 'GEN', name: 'Gen Digital Inc.', sector: 'Technology', subsector: 'Software' },

  // Communication Services
  { ticker: 'GOOGL', name: 'Alphabet Inc. Class A', sector: 'Communication Services', subsector: 'Interactive Media' },
  { ticker: 'GOOG', name: 'Alphabet Inc. Class C', sector: 'Communication Services', subsector: 'Interactive Media' },
  { ticker: 'META', name: 'Meta Platforms', sector: 'Communication Services', subsector: 'Interactive Media' },
  { ticker: 'NFLX', name: 'Netflix Inc.', sector: 'Communication Services', subsector: 'Entertainment' },
  { ticker: 'DIS', name: 'Walt Disney Co.', sector: 'Communication Services', subsector: 'Entertainment' },
  { ticker: 'CMCSA', name: 'Comcast Corp.', sector: 'Communication Services', subsector: 'Cable & Satellite' },
  { ticker: 'T', name: 'AT&T Inc.', sector: 'Communication Services', subsector: 'Diversified Telecom' },
  { ticker: 'VZ', name: 'Verizon Communications', sector: 'Communication Services', subsector: 'Diversified Telecom' },
  { ticker: 'TMUS', name: 'T-Mobile US', sector: 'Communication Services', subsector: 'Wireless Telecom' },
  { ticker: 'CHTR', name: 'Charter Communications', sector: 'Communication Services', subsector: 'Cable & Satellite' },
  { ticker: 'FOXA', name: 'Fox Corp. Class A', sector: 'Communication Services', subsector: 'Entertainment' },
  { ticker: 'WBD', name: 'Warner Bros. Discovery', sector: 'Communication Services', subsector: 'Entertainment' },
  { ticker: 'OMC', name: 'Omnicom Group', sector: 'Communication Services', subsector: 'Media' },
  { ticker: 'IPG', name: 'Interpublic Group', sector: 'Communication Services', subsector: 'Media' },
  { ticker: 'EA', name: 'Electronic Arts', sector: 'Communication Services', subsector: 'Entertainment' },
  { ticker: 'TTWO', name: 'Take-Two Interactive', sector: 'Communication Services', subsector: 'Entertainment' },
  { ticker: 'MTCH', name: 'Match Group', sector: 'Communication Services', subsector: 'Interactive Media' },
  { ticker: 'PINS', name: 'Pinterest Inc.', sector: 'Communication Services', subsector: 'Interactive Media' },

  // Consumer Discretionary
  { ticker: 'AMZN', name: 'Amazon.com Inc.', sector: 'Consumer Discretionary', subsector: 'Internet Retail' },
  { ticker: 'TSLA', name: 'Tesla Inc.', sector: 'Consumer Discretionary', subsector: 'Automobiles' },
  { ticker: 'HD', name: 'Home Depot Inc.', sector: 'Consumer Discretionary', subsector: 'Home Improvement Retail' },
  { ticker: 'MCD', name: "McDonald's Corp.", sector: 'Consumer Discretionary', subsector: 'Restaurants' },
  { ticker: 'NKE', name: 'Nike Inc.', sector: 'Consumer Discretionary', subsector: 'Apparel' },
  { ticker: 'SBUX', name: 'Starbucks Corp.', sector: 'Consumer Discretionary', subsector: 'Restaurants' },
  { ticker: 'TJX', name: 'TJX Companies', sector: 'Consumer Discretionary', subsector: 'Apparel Retail' },
  { ticker: 'BKNG', name: 'Booking Holdings', sector: 'Consumer Discretionary', subsector: 'Internet Retail' },
  { ticker: 'LOW', name: "Lowe's Companies", sector: 'Consumer Discretionary', subsector: 'Home Improvement Retail' },
  { ticker: 'MAR', name: 'Marriott International', sector: 'Consumer Discretionary', subsector: 'Hotels' },
  { ticker: 'HLT', name: 'Hilton Worldwide', sector: 'Consumer Discretionary', subsector: 'Hotels' },
  { ticker: 'CMG', name: 'Chipotle Mexican Grill', sector: 'Consumer Discretionary', subsector: 'Restaurants' },
  { ticker: 'ORLY', name: "O'Reilly Automotive", sector: 'Consumer Discretionary', subsector: 'Specialty Retail' },
  { ticker: 'AZO', name: 'AutoZone Inc.', sector: 'Consumer Discretionary', subsector: 'Specialty Retail' },
  { ticker: 'GM', name: 'General Motors', sector: 'Consumer Discretionary', subsector: 'Automobiles' },
  { ticker: 'F', name: 'Ford Motor Co.', sector: 'Consumer Discretionary', subsector: 'Automobiles' },
  { ticker: 'EBAY', name: 'eBay Inc.', sector: 'Consumer Discretionary', subsector: 'Internet Retail' },
  { ticker: 'YUM', name: 'Yum! Brands', sector: 'Consumer Discretionary', subsector: 'Restaurants' },
  { ticker: 'DPZ', name: "Domino's Pizza", sector: 'Consumer Discretionary', subsector: 'Restaurants' },
  { ticker: 'APTV', name: 'Aptiv PLC', sector: 'Consumer Discretionary', subsector: 'Auto Parts' },
  { ticker: 'GRMN', name: 'Garmin Ltd.', sector: 'Consumer Discretionary', subsector: 'Electronic Equipment' },
  { ticker: 'RCL', name: 'Royal Caribbean', sector: 'Consumer Discretionary', subsector: 'Hotels' },
  { ticker: 'CCL', name: 'Carnival Corp.', sector: 'Consumer Discretionary', subsector: 'Hotels' },
  { ticker: 'EXPE', name: 'Expedia Group', sector: 'Consumer Discretionary', subsector: 'Internet Retail' },
  { ticker: 'LVS', name: 'Las Vegas Sands', sector: 'Consumer Discretionary', subsector: 'Casinos' },
  { ticker: 'WYNN', name: 'Wynn Resorts', sector: 'Consumer Discretionary', subsector: 'Casinos' },
  { ticker: 'MGM', name: 'MGM Resorts', sector: 'Consumer Discretionary', subsector: 'Casinos' },
  { ticker: 'PHM', name: 'PulteGroup Inc.', sector: 'Consumer Discretionary', subsector: 'Homebuilding' },
  { ticker: 'DHI', name: 'D.R. Horton', sector: 'Consumer Discretionary', subsector: 'Homebuilding' },
  { ticker: 'LEN', name: 'Lennar Corp.', sector: 'Consumer Discretionary', subsector: 'Homebuilding' },
  { ticker: 'NVR', name: 'NVR Inc.', sector: 'Consumer Discretionary', subsector: 'Homebuilding' },
  { ticker: 'TOL', name: 'Toll Brothers', sector: 'Consumer Discretionary', subsector: 'Homebuilding' },
  { ticker: 'RL', name: 'Ralph Lauren', sector: 'Consumer Discretionary', subsector: 'Apparel' },
  { ticker: 'PVH', name: 'PVH Corp.', sector: 'Consumer Discretionary', subsector: 'Apparel' },
  { ticker: 'VFC', name: 'VF Corp.', sector: 'Consumer Discretionary', subsector: 'Apparel' },
  { ticker: 'HAS', name: 'Hasbro Inc.', sector: 'Consumer Discretionary', subsector: 'Leisure Products' },
  { ticker: 'MHK', name: 'Mohawk Industries', sector: 'Consumer Discretionary', subsector: 'Home Furnishings' },

  // Consumer Staples
  { ticker: 'WMT', name: 'Walmart Inc.', sector: 'Consumer Staples', subsector: 'Hypermarkets' },
  { ticker: 'COST', name: 'Costco Wholesale', sector: 'Consumer Staples', subsector: 'Hypermarkets' },
  { ticker: 'PG', name: 'Procter & Gamble', sector: 'Consumer Staples', subsector: 'Household Products' },
  { ticker: 'KO', name: 'Coca-Cola Co.', sector: 'Consumer Staples', subsector: 'Beverages' },
  { ticker: 'PEP', name: 'PepsiCo Inc.', sector: 'Consumer Staples', subsector: 'Beverages' },
  { ticker: 'PM', name: 'Philip Morris International', sector: 'Consumer Staples', subsector: 'Tobacco' },
  { ticker: 'MO', name: 'Altria Group', sector: 'Consumer Staples', subsector: 'Tobacco' },
  { ticker: 'MDLZ', name: 'Mondelez International', sector: 'Consumer Staples', subsector: 'Food Products' },
  { ticker: 'CL', name: 'Colgate-Palmolive', sector: 'Consumer Staples', subsector: 'Household Products' },
  { ticker: 'GIS', name: 'General Mills', sector: 'Consumer Staples', subsector: 'Food Products' },
  { ticker: 'FRPT', name: 'Freshpet Inc.', sector: 'Consumer Staples', subsector: 'Food Products' },
  { ticker: 'KHC', name: 'Kraft Heinz Co.', sector: 'Consumer Staples', subsector: 'Food Products' },
  { ticker: 'CAG', name: 'Conagra Brands', sector: 'Consumer Staples', subsector: 'Food Products' },
  { ticker: 'CPB', name: "Campbell Soup", sector: 'Consumer Staples', subsector: 'Food Products' },
  { ticker: 'HSY', name: 'Hershey Co.', sector: 'Consumer Staples', subsector: 'Food Products' },
  { ticker: 'MKC', name: 'McCormick & Co.', sector: 'Consumer Staples', subsector: 'Food Products' },
  { ticker: 'SJM', name: 'J.M. Smucker', sector: 'Consumer Staples', subsector: 'Food Products' },
  { ticker: 'CLX', name: 'Clorox Co.', sector: 'Consumer Staples', subsector: 'Household Products' },
  { ticker: 'CHD', name: 'Church & Dwight', sector: 'Consumer Staples', subsector: 'Household Products' },
  { ticker: 'EL', name: 'Estee Lauder', sector: 'Consumer Staples', subsector: 'Personal Products' },
  { ticker: 'KVUE', name: 'Kenvue Inc.', sector: 'Consumer Staples', subsector: 'Personal Products' },
  { ticker: 'SYY', name: 'Sysco Corp.', sector: 'Consumer Staples', subsector: 'Food Distributors' },
  { ticker: 'KR', name: 'Kroger Co.', sector: 'Consumer Staples', subsector: 'Food Retail' },
  { ticker: 'TSN', name: 'Tyson Foods', sector: 'Consumer Staples', subsector: 'Food Products' },
  { ticker: 'HRL', name: 'Hormel Foods', sector: 'Consumer Staples', subsector: 'Food Products' },
  { ticker: 'TAP', name: 'Molson Coors Beverage', sector: 'Consumer Staples', subsector: 'Beverages' },
  { ticker: 'STZ', name: 'Constellation Brands', sector: 'Consumer Staples', subsector: 'Beverages' },
  { ticker: 'BF-B', name: 'Brown-Forman Corp.', sector: 'Consumer Staples', subsector: 'Beverages' },

  // Healthcare
  { ticker: 'UNH', name: 'UnitedHealth Group', sector: 'Healthcare', subsector: 'Managed Care' },
  { ticker: 'LLY', name: 'Eli Lilly & Co.', sector: 'Healthcare', subsector: 'Pharmaceuticals' },
  { ticker: 'JNJ', name: 'Johnson & Johnson', sector: 'Healthcare', subsector: 'Pharmaceuticals' },
  { ticker: 'ABT', name: 'Abbott Laboratories', sector: 'Healthcare', subsector: 'Health Care Equipment' },
  { ticker: 'MRK', name: 'Merck & Co.', sector: 'Healthcare', subsector: 'Pharmaceuticals' },
  { ticker: 'TMO', name: 'Thermo Fisher Scientific', sector: 'Healthcare', subsector: 'Life Sciences' },
  { ticker: 'DHR', name: 'Danaher Corp.', sector: 'Healthcare', subsector: 'Life Sciences' },
  { ticker: 'ABBV', name: 'AbbVie Inc.', sector: 'Healthcare', subsector: 'Biotechnology' },
  { ticker: 'BMY', name: 'Bristol-Myers Squibb', sector: 'Healthcare', subsector: 'Pharmaceuticals' },
  { ticker: 'AMGN', name: 'Amgen Inc.', sector: 'Healthcare', subsector: 'Biotechnology' },
  { ticker: 'GILD', name: 'Gilead Sciences', sector: 'Healthcare', subsector: 'Biotechnology' },
  { ticker: 'VRTX', name: 'Vertex Pharmaceuticals', sector: 'Healthcare', subsector: 'Biotechnology' },
  { ticker: 'REGN', name: 'Regeneron Pharmaceuticals', sector: 'Healthcare', subsector: 'Biotechnology' },
  { ticker: 'BIIB', name: 'Biogen Inc.', sector: 'Healthcare', subsector: 'Biotechnology' },
  { ticker: 'MRNA', name: 'Moderna Inc.', sector: 'Healthcare', subsector: 'Biotechnology' },
  { ticker: 'SYK', name: 'Stryker Corp.', sector: 'Healthcare', subsector: 'Health Care Equipment' },
  { ticker: 'BDX', name: 'Becton Dickinson', sector: 'Healthcare', subsector: 'Health Care Equipment' },
  { ticker: 'MDT', name: 'Medtronic PLC', sector: 'Healthcare', subsector: 'Health Care Equipment' },
  { ticker: 'EW', name: 'Edwards Lifesciences', sector: 'Healthcare', subsector: 'Health Care Equipment' },
  { ticker: 'ISRG', name: 'Intuitive Surgical', sector: 'Healthcare', subsector: 'Health Care Equipment' },
  { ticker: 'BSX', name: 'Boston Scientific', sector: 'Healthcare', subsector: 'Health Care Equipment' },
  { ticker: 'ZBH', name: 'Zimmer Biomet', sector: 'Healthcare', subsector: 'Health Care Equipment' },
  { ticker: 'DXCM', name: 'DexCom Inc.', sector: 'Healthcare', subsector: 'Health Care Equipment' },
  { ticker: 'HCA', name: 'HCA Healthcare', sector: 'Healthcare', subsector: 'Health Care Facilities' },
  { ticker: 'CI', name: 'Cigna Group', sector: 'Healthcare', subsector: 'Managed Care' },
  { ticker: 'ELV', name: 'Elevance Health', sector: 'Healthcare', subsector: 'Managed Care' },
  { ticker: 'HUM', name: 'Humana Inc.', sector: 'Healthcare', subsector: 'Managed Care' },
  { ticker: 'CNC', name: 'Centene Corp.', sector: 'Healthcare', subsector: 'Managed Care' },
  { ticker: 'MCK', name: 'McKesson Corp.', sector: 'Healthcare', subsector: 'Health Care Distributors' },
  { ticker: 'CAH', name: 'Cardinal Health', sector: 'Healthcare', subsector: 'Health Care Distributors' },
  { ticker: 'COR', name: 'Cencora Inc.', sector: 'Healthcare', subsector: 'Health Care Distributors' },
  { ticker: 'CVS', name: 'CVS Health', sector: 'Healthcare', subsector: 'Health Care Services' },
  { ticker: 'A', name: 'Agilent Technologies', sector: 'Healthcare', subsector: 'Life Sciences' },
  { ticker: 'IQV', name: 'IQVIA Holdings', sector: 'Healthcare', subsector: 'Life Sciences' },
  { ticker: 'INVA', name: 'Innoviva Inc.', sector: 'Healthcare', subsector: 'Pharmaceuticals' },
  { ticker: 'PFE', name: 'Pfizer Inc.', sector: 'Healthcare', subsector: 'Pharmaceuticals' },
  { ticker: 'GEHC', name: 'GE HealthCare', sector: 'Healthcare', subsector: 'Health Care Equipment' },
  { ticker: 'ZTS', name: 'Zoetis Inc.', sector: 'Healthcare', subsector: 'Pharmaceuticals' },
  { ticker: 'IDXX', name: 'IDEXX Laboratories', sector: 'Healthcare', subsector: 'Health Care Equipment' },
  { ticker: 'HOLX', name: 'Hologic Inc.', sector: 'Healthcare', subsector: 'Health Care Equipment' },

  // Financials
  { ticker: 'BRK.B', name: 'Berkshire Hathaway B', sector: 'Financials', subsector: 'Multi-line Insurance' },
  { ticker: 'JPM', name: 'JPMorgan Chase', sector: 'Financials', subsector: 'Diversified Banks' },
  { ticker: 'BAC', name: 'Bank of America', sector: 'Financials', subsector: 'Diversified Banks' },
  { ticker: 'WFC', name: 'Wells Fargo', sector: 'Financials', subsector: 'Diversified Banks' },
  { ticker: 'GS', name: 'Goldman Sachs', sector: 'Financials', subsector: 'Investment Banking' },
  { ticker: 'MS', name: 'Morgan Stanley', sector: 'Financials', subsector: 'Investment Banking' },
  { ticker: 'C', name: 'Citigroup Inc.', sector: 'Financials', subsector: 'Diversified Banks' },
  { ticker: 'BLK', name: 'BlackRock Inc.', sector: 'Financials', subsector: 'Asset Management' },
  { ticker: 'CB', name: 'Chubb Ltd.', sector: 'Financials', subsector: 'Property & Casualty Insurance' },
  { ticker: 'PGR', name: 'Progressive Corp.', sector: 'Financials', subsector: 'Property & Casualty Insurance' },
  { ticker: 'AXP', name: 'American Express', sector: 'Financials', subsector: 'Consumer Finance' },
  { ticker: 'USB', name: 'U.S. Bancorp', sector: 'Financials', subsector: 'Diversified Banks' },
  { ticker: 'TFC', name: 'Truist Financial', sector: 'Financials', subsector: 'Diversified Banks' },
  { ticker: 'PNC', name: 'PNC Financial Services', sector: 'Financials', subsector: 'Diversified Banks' },
  { ticker: 'COF', name: 'Capital One Financial', sector: 'Financials', subsector: 'Consumer Finance' },
  { ticker: 'SPGI', name: 'S&P Global', sector: 'Financials', subsector: 'Financial Data & Analytics' },
  { ticker: 'MCO', name: "Moody's Corp.", sector: 'Financials', subsector: 'Financial Data & Analytics' },
  { ticker: 'ICE', name: 'Intercontinental Exchange', sector: 'Financials', subsector: 'Financial Exchanges' },
  { ticker: 'CME', name: 'CME Group', sector: 'Financials', subsector: 'Financial Exchanges' },
  { ticker: 'AON', name: 'Aon PLC', sector: 'Financials', subsector: 'Insurance Brokers' },
  { ticker: 'MMC', name: 'Marsh McLennan', sector: 'Financials', subsector: 'Insurance Brokers' },
  { ticker: 'AIG', name: 'American International Group', sector: 'Financials', subsector: 'Multi-line Insurance' },
  { ticker: 'MET', name: 'MetLife Inc.', sector: 'Financials', subsector: 'Life Insurance' },
  { ticker: 'PRU', name: 'Prudential Financial', sector: 'Financials', subsector: 'Life Insurance' },
  { ticker: 'AFL', name: 'Aflac Inc.', sector: 'Financials', subsector: 'Life Insurance' },
  { ticker: 'ALL', name: 'Allstate Corp.', sector: 'Financials', subsector: 'Property & Casualty Insurance' },
  { ticker: 'SCHW', name: 'Charles Schwab', sector: 'Financials', subsector: 'Investment Banking' },
  { ticker: 'BK', name: 'Bank of New York Mellon', sector: 'Financials', subsector: 'Asset Management' },
  { ticker: 'STT', name: 'State Street Corp.', sector: 'Financials', subsector: 'Asset Management' },
  { ticker: 'FIS', name: 'Fidelity National Information Services', sector: 'Financials', subsector: 'Data Processing' },
  { ticker: 'FISV', name: 'Fiserv Inc.', sector: 'Financials', subsector: 'Data Processing' },
  { ticker: 'GPN', name: 'Global Payments', sector: 'Financials', subsector: 'Data Processing' },
  { ticker: 'NDAQ', name: 'Nasdaq Inc.', sector: 'Financials', subsector: 'Financial Exchanges' },
  { ticker: 'CBOE', name: 'Cboe Global Markets', sector: 'Financials', subsector: 'Financial Exchanges' },
  { ticker: 'RF', name: 'Regions Financial', sector: 'Financials', subsector: 'Regional Banks' },
  { ticker: 'KEY', name: 'KeyCorp', sector: 'Financials', subsector: 'Regional Banks' },
  { ticker: 'FITB', name: 'Fifth Third Bancorp', sector: 'Financials', subsector: 'Regional Banks' },
  { ticker: 'HBAN', name: 'Huntington Bancshares', sector: 'Financials', subsector: 'Regional Banks' },
  { ticker: 'MTB', name: 'M&T Bank Corp.', sector: 'Financials', subsector: 'Regional Banks' },
  { ticker: 'CFG', name: 'Citizens Financial Group', sector: 'Financials', subsector: 'Regional Banks' },
  { ticker: 'ALLY', name: 'Ally Financial', sector: 'Financials', subsector: 'Consumer Finance' },
  { ticker: 'SNA', name: 'Snap-on Inc.', sector: 'Industrials', subsector: 'Industrial Machinery' },
  { ticker: 'SYF', name: 'Synchrony Financial', sector: 'Financials', subsector: 'Consumer Finance' },

  // Industrials
  { ticker: 'CAT', name: 'Caterpillar Inc.', sector: 'Industrials', subsector: 'Construction Machinery' },
  { ticker: 'DE', name: 'Deere & Co.', sector: 'Industrials', subsector: 'Agricultural Machinery' },
  { ticker: 'HON', name: 'Honeywell International', sector: 'Industrials', subsector: 'Industrial Conglomerates' },
  { ticker: 'RTX', name: 'RTX Corp.', sector: 'Industrials', subsector: 'Aerospace & Defense' },
  { ticker: 'LMT', name: 'Lockheed Martin', sector: 'Industrials', subsector: 'Aerospace & Defense' },
  { ticker: 'GE', name: 'GE Aerospace', sector: 'Industrials', subsector: 'Aerospace & Defense' },
  { ticker: 'UPS', name: 'United Parcel Service', sector: 'Industrials', subsector: 'Air Freight' },
  { ticker: 'FDX', name: 'FedEx Corp.', sector: 'Industrials', subsector: 'Air Freight' },
  { ticker: 'BA', name: 'Boeing Co.', sector: 'Industrials', subsector: 'Aerospace & Defense' },
  { ticker: 'NOC', name: 'Northrop Grumman', sector: 'Industrials', subsector: 'Aerospace & Defense' },
  { ticker: 'GD', name: 'General Dynamics', sector: 'Industrials', subsector: 'Aerospace & Defense' },
  { ticker: 'LHX', name: 'L3Harris Technologies', sector: 'Industrials', subsector: 'Aerospace & Defense' },
  { ticker: 'HII', name: 'Huntington Ingalls Industries', sector: 'Industrials', subsector: 'Aerospace & Defense' },
  { ticker: 'MMM', name: '3M Co.', sector: 'Industrials', subsector: 'Industrial Conglomerates' },
  { ticker: 'EMR', name: 'Emerson Electric', sector: 'Industrials', subsector: 'Industrial Machinery' },
  { ticker: 'ETN', name: 'Eaton Corp.', sector: 'Industrials', subsector: 'Electrical Components' },
  { ticker: 'PH', name: 'Parker Hannifin', sector: 'Industrials', subsector: 'Industrial Machinery' },
  { ticker: 'ROK', name: 'Rockwell Automation', sector: 'Industrials', subsector: 'Industrial Machinery' },
  { ticker: 'ITW', name: 'Illinois Tool Works', sector: 'Industrials', subsector: 'Industrial Machinery' },
  { ticker: 'DOV', name: 'Dover Corp.', sector: 'Industrials', subsector: 'Industrial Machinery' },
  { ticker: 'XYL', name: 'Xylem Inc.', sector: 'Industrials', subsector: 'Industrial Machinery' },
  { ticker: 'CARR', name: 'Carrier Global', sector: 'Industrials', subsector: 'Building Products' },
  { ticker: 'OTIS', name: 'Otis Worldwide', sector: 'Industrials', subsector: 'Industrial Machinery' },
  { ticker: 'TT', name: 'Trane Technologies', sector: 'Industrials', subsector: 'Building Products' },
  { ticker: 'JCI', name: 'Johnson Controls', sector: 'Industrials', subsector: 'Building Products' },
  { ticker: 'PCAR', name: 'PACCAR Inc.', sector: 'Industrials', subsector: 'Construction Machinery' },
  { ticker: 'CSX', name: 'CSX Corp.', sector: 'Industrials', subsector: 'Railroads' },
  { ticker: 'UNP', name: 'Union Pacific', sector: 'Industrials', subsector: 'Railroads' },
  { ticker: 'NSC', name: 'Norfolk Southern', sector: 'Industrials', subsector: 'Railroads' },
  { ticker: 'DAL', name: 'Delta Air Lines', sector: 'Industrials', subsector: 'Airlines' },
  { ticker: 'UAL', name: 'United Airlines', sector: 'Industrials', subsector: 'Airlines' },
  { ticker: 'AAL', name: 'American Airlines', sector: 'Industrials', subsector: 'Airlines' },
  { ticker: 'LUV', name: 'Southwest Airlines', sector: 'Industrials', subsector: 'Airlines' },
  { ticker: 'CTAS', name: 'Cintas Corp.', sector: 'Industrials', subsector: 'Commercial Services' },
  { ticker: 'RSG', name: 'Republic Services', sector: 'Industrials', subsector: 'Environmental Services' },
  { ticker: 'WM', name: 'Waste Management', sector: 'Industrials', subsector: 'Environmental Services' },
  { ticker: 'VRSK', name: 'Verisk Analytics', sector: 'Industrials', subsector: 'Research & Consulting' },
  { ticker: 'EFX', name: 'Equifax Inc.', sector: 'Industrials', subsector: 'Research & Consulting' },
  { ticker: 'CPRT', name: 'Copart Inc.', sector: 'Industrials', subsector: 'Commercial Services' },

  // Energy
  { ticker: 'XOM', name: 'Exxon Mobil', sector: 'Energy', subsector: 'Integrated Oil & Gas' },
  { ticker: 'CVX', name: 'Chevron Corp.', sector: 'Energy', subsector: 'Integrated Oil & Gas' },
  { ticker: 'COP', name: 'ConocoPhillips', sector: 'Energy', subsector: 'Oil & Gas Exploration' },
  { ticker: 'EOG', name: 'EOG Resources', sector: 'Energy', subsector: 'Oil & Gas Exploration' },
  { ticker: 'SLB', name: 'Schlumberger Ltd.', sector: 'Energy', subsector: 'Oil & Gas Equipment' },
  { ticker: 'PSX', name: 'Phillips 66', sector: 'Energy', subsector: 'Oil & Gas Refining' },
  { ticker: 'VLO', name: 'Valero Energy', sector: 'Energy', subsector: 'Oil & Gas Refining' },
  { ticker: 'MPC', name: 'Marathon Petroleum', sector: 'Energy', subsector: 'Oil & Gas Refining' },
  { ticker: 'OXY', name: 'Occidental Petroleum', sector: 'Energy', subsector: 'Oil & Gas Exploration' },
  { ticker: 'KMI', name: 'Kinder Morgan', sector: 'Energy', subsector: 'Oil & Gas Storage' },
  { ticker: 'WMB', name: 'Williams Companies', sector: 'Energy', subsector: 'Oil & Gas Storage' },
  { ticker: 'LNG', name: 'Cheniere Energy', sector: 'Energy', subsector: 'Oil & Gas Storage' },
  { ticker: 'DVN', name: 'Devon Energy', sector: 'Energy', subsector: 'Oil & Gas Exploration' },
  { ticker: 'FANG', name: 'Diamondback Energy', sector: 'Energy', subsector: 'Oil & Gas Exploration' },
  { ticker: 'HAL', name: 'Halliburton Co.', sector: 'Energy', subsector: 'Oil & Gas Equipment' },
  { ticker: 'BKR', name: 'Baker Hughes', sector: 'Energy', subsector: 'Oil & Gas Equipment' },
  { ticker: 'MTDR', name: 'Matador Resources', sector: 'Energy', subsector: 'Oil & Gas Exploration' },
  { ticker: 'CTRA', name: 'Coterra Energy', sector: 'Energy', subsector: 'Oil & Gas Exploration' },
  { ticker: 'APA', name: 'APA Corp.', sector: 'Energy', subsector: 'Oil & Gas Exploration' },

  // Materials
  { ticker: 'LIN', name: 'Linde PLC', sector: 'Materials', subsector: 'Industrial Gases' },
  { ticker: 'APD', name: 'Air Products and Chemicals', sector: 'Materials', subsector: 'Industrial Gases' },
  { ticker: 'ECL', name: 'Ecolab Inc.', sector: 'Materials', subsector: 'Specialty Chemicals' },
  { ticker: 'SHW', name: 'Sherwin-Williams', sector: 'Materials', subsector: 'Specialty Chemicals' },
  { ticker: 'FCX', name: 'Freeport-McMoRan', sector: 'Materials', subsector: 'Copper' },
  { ticker: 'NEM', name: 'Newmont Corp.', sector: 'Materials', subsector: 'Gold' },
  { ticker: 'NUE', name: 'Nucor Corp.', sector: 'Materials', subsector: 'Steel' },
  { ticker: 'VMC', name: 'Vulcan Materials', sector: 'Materials', subsector: 'Construction Materials' },
  { ticker: 'MLM', name: 'Martin Marietta Materials', sector: 'Materials', subsector: 'Construction Materials' },
  { ticker: 'CF', name: 'CF Industries', sector: 'Materials', subsector: 'Fertilizers & Agricultural Chemicals' },
  { ticker: 'MOS', name: 'Mosaic Co.', sector: 'Materials', subsector: 'Fertilizers & Agricultural Chemicals' },
  { ticker: 'DOW', name: 'Dow Inc.', sector: 'Materials', subsector: 'Commodity Chemicals' },
  { ticker: 'LYB', name: 'LyondellBasell Industries', sector: 'Materials', subsector: 'Commodity Chemicals' },
  { ticker: 'PPG', name: 'PPG Industries', sector: 'Materials', subsector: 'Specialty Chemicals' },
  { ticker: 'IP', name: 'International Paper', sector: 'Materials', subsector: 'Paper Products' },
  { ticker: 'PKG', name: 'Packaging Corp. of America', sector: 'Materials', subsector: 'Paper Products' },
  { ticker: 'SEE', name: 'Sealed Air Corp.', sector: 'Materials', subsector: 'Packaging' },
  { ticker: 'BALL', name: 'Ball Corp.', sector: 'Materials', subsector: 'Metal & Glass Containers' },

  // Real Estate
  { ticker: 'AMT', name: 'American Tower', sector: 'Real Estate', subsector: 'Specialized REITs' },
  { ticker: 'PLD', name: 'Prologis Inc.', sector: 'Real Estate', subsector: 'Industrial REITs' },
  { ticker: 'EQIX', name: 'Equinix Inc.', sector: 'Real Estate', subsector: 'Specialized REITs' },
  { ticker: 'CCI', name: 'Crown Castle', sector: 'Real Estate', subsector: 'Specialized REITs' },
  { ticker: 'DLR', name: 'Digital Realty Trust', sector: 'Real Estate', subsector: 'Specialized REITs' },
  { ticker: 'PSA', name: 'Public Storage', sector: 'Real Estate', subsector: 'Specialized REITs' },
  { ticker: 'SPG', name: 'Simon Property Group', sector: 'Real Estate', subsector: 'Retail REITs' },
  { ticker: 'O', name: 'Realty Income Corp.', sector: 'Real Estate', subsector: 'Retail REITs' },
  { ticker: 'VICI', name: 'VICI Properties', sector: 'Real Estate', subsector: 'Specialized REITs' },
  { ticker: 'EXR', name: 'Extra Space Storage', sector: 'Real Estate', subsector: 'Specialized REITs' },
  { ticker: 'WY', name: 'Weyerhaeuser Co.', sector: 'Real Estate', subsector: 'Specialized REITs' },
  { ticker: 'AVB', name: 'AvalonBay Communities', sector: 'Real Estate', subsector: 'Residential REITs' },
  { ticker: 'EQR', name: 'Equity Residential', sector: 'Real Estate', subsector: 'Residential REITs' },
  { ticker: 'ESS', name: 'Essex Property Trust', sector: 'Real Estate', subsector: 'Residential REITs' },
  { ticker: 'MAA', name: 'Mid-America Apartment', sector: 'Real Estate', subsector: 'Residential REITs' },
  { ticker: 'UDR', name: 'UDR Inc.', sector: 'Real Estate', subsector: 'Residential REITs' },
  { ticker: 'CPT', name: 'Camden Property Trust', sector: 'Real Estate', subsector: 'Residential REITs' },
  { ticker: 'IRM', name: 'Iron Mountain', sector: 'Real Estate', subsector: 'Specialized REITs' },
  { ticker: 'HST', name: 'Host Hotels & Resorts', sector: 'Real Estate', subsector: 'Hotel & Resort REITs' },
  { ticker: 'REG', name: 'Regency Centers', sector: 'Real Estate', subsector: 'Retail REITs' },
  { ticker: 'KIM', name: 'Kimco Realty', sector: 'Real Estate', subsector: 'Retail REITs' },
  { ticker: 'FRT', name: 'Federal Realty Investment Trust', sector: 'Real Estate', subsector: 'Retail REITs' },

  // Utilities
  { ticker: 'NEE', name: 'NextEra Energy', sector: 'Utilities', subsector: 'Electric Utilities' },
  { ticker: 'DUK', name: 'Duke Energy', sector: 'Utilities', subsector: 'Electric Utilities' },
  { ticker: 'SO', name: 'Southern Co.', sector: 'Utilities', subsector: 'Electric Utilities' },
  { ticker: 'AEP', name: 'American Electric Power', sector: 'Utilities', subsector: 'Electric Utilities' },
  { ticker: 'SRE', name: 'Sempra Energy', sector: 'Utilities', subsector: 'Multi-Utilities' },
  { ticker: 'PCG', name: 'PG&E Corp.', sector: 'Utilities', subsector: 'Electric Utilities' },
  { ticker: 'EXC', name: 'Exelon Corp.', sector: 'Utilities', subsector: 'Electric Utilities' },
  { ticker: 'XEL', name: 'Xcel Energy', sector: 'Utilities', subsector: 'Electric Utilities' },
  { ticker: 'WEC', name: 'WEC Energy Group', sector: 'Utilities', subsector: 'Electric Utilities' },
  { ticker: 'ES', name: 'Eversource Energy', sector: 'Utilities', subsector: 'Electric Utilities' },
  { ticker: 'DTE', name: 'DTE Energy', sector: 'Utilities', subsector: 'Multi-Utilities' },
  { ticker: 'PPL', name: 'PPL Corp.', sector: 'Utilities', subsector: 'Electric Utilities' },
  { ticker: 'CNP', name: 'CenterPoint Energy', sector: 'Utilities', subsector: 'Multi-Utilities' },
  { ticker: 'NI', name: 'NiSource Inc.', sector: 'Utilities', subsector: 'Gas Utilities' },
  { ticker: 'AES', name: 'AES Corp.', sector: 'Utilities', subsector: 'Independent Power Producers' },
  { ticker: 'ETR', name: 'Entergy Corp.', sector: 'Utilities', subsector: 'Electric Utilities' },
  { ticker: 'FE', name: 'FirstEnergy Corp.', sector: 'Utilities', subsector: 'Electric Utilities' },
  { ticker: 'EIX', name: 'Edison International', sector: 'Utilities', subsector: 'Electric Utilities' },
  { ticker: 'AWK', name: 'American Water Works', sector: 'Utilities', subsector: 'Water Utilities' },
  { ticker: 'EVRG', name: 'Evergy Inc.', sector: 'Utilities', subsector: 'Electric Utilities' },
  { ticker: 'LNT', name: 'Alliant Energy', sector: 'Utilities', subsector: 'Electric Utilities' },
  { ticker: 'PNW', name: 'Pinnacle West Capital', sector: 'Utilities', subsector: 'Electric Utilities' },

  // Payment Networks (cross-sector, often grouped with Financials but distinct)
  { ticker: 'V', name: 'Visa Inc.', sector: 'Financials', subsector: 'Transaction & Payment Processing' },
  { ticker: 'MA', name: 'Mastercard Inc.', sector: 'Financials', subsector: 'Transaction & Payment Processing' },
  { ticker: 'PYPL', name: 'PayPal Holdings', sector: 'Financials', subsector: 'Transaction & Payment Processing' },
  { ticker: 'SQ', name: 'Block Inc.', sector: 'Financials', subsector: 'Transaction & Payment Processing' },

  // Additional high-cap stocks across sectors
  { ticker: 'UBER', name: 'Uber Technologies', sector: 'Industrials', subsector: 'Ground Transportation' },
  { ticker: 'LYFT', name: 'Lyft Inc.', sector: 'Industrials', subsector: 'Ground Transportation' },
  { ticker: 'ABNB', name: 'Airbnb Inc.', sector: 'Consumer Discretionary', subsector: 'Hotels' },
  { ticker: 'DASH', name: 'DoorDash Inc.', sector: 'Consumer Discretionary', subsector: 'Internet Retail' },
  { ticker: 'SNOW', name: 'Snowflake Inc.', sector: 'Technology', subsector: 'Software' },
  { ticker: 'PLTR', name: 'Palantir Technologies', sector: 'Technology', subsector: 'Software' },
  { ticker: 'NET', name: 'Cloudflare Inc.', sector: 'Technology', subsector: 'Software' },
  { ticker: 'CRWD', name: 'CrowdStrike Holdings', sector: 'Technology', subsector: 'Software' },
  { ticker: 'ZS', name: 'Zscaler Inc.', sector: 'Technology', subsector: 'Software' },
  { ticker: 'OKTA', name: 'Okta Inc.', sector: 'Technology', subsector: 'Software' },
  { ticker: 'DDOG', name: 'Datadog Inc.', sector: 'Technology', subsector: 'Software' },
  { ticker: 'MDB', name: 'MongoDB Inc.', sector: 'Technology', subsector: 'Software' },
  { ticker: 'SHOP', name: 'Shopify Inc.', sector: 'Consumer Discretionary', subsector: 'Internet Retail' },
  { ticker: 'SE', name: 'Sea Limited', sector: 'Consumer Discretionary', subsector: 'Internet Retail' },
  { ticker: 'MELI', name: 'MercadoLibre Inc.', sector: 'Consumer Discretionary', subsector: 'Internet Retail' },
  { ticker: 'SPOT', name: 'Spotify Technology', sector: 'Communication Services', subsector: 'Entertainment' },
  { ticker: 'RBLX', name: 'Roblox Corp.', sector: 'Communication Services', subsector: 'Entertainment' },
  { ticker: 'U', name: 'Unity Software', sector: 'Technology', subsector: 'Software' },
  { ticker: 'COIN', name: 'Coinbase Global', sector: 'Financials', subsector: 'Financial Exchanges' },
  { ticker: 'HOOD', name: 'Robinhood Markets', sector: 'Financials', subsector: 'Investment Banking' },
  { ticker: 'SOFI', name: 'SoFi Technologies', sector: 'Financials', subsector: 'Consumer Finance' },
  { ticker: 'AFRM', name: 'Affirm Holdings', sector: 'Financials', subsector: 'Consumer Finance' },
  { ticker: 'RIVN', name: 'Rivian Automotive', sector: 'Consumer Discretionary', subsector: 'Automobiles' },
  { ticker: 'LCID', name: 'Lucid Group', sector: 'Consumer Discretionary', subsector: 'Automobiles' },
  { ticker: 'NIO', name: 'NIO Inc.', sector: 'Consumer Discretionary', subsector: 'Automobiles' },
  { ticker: 'LI', name: 'Li Auto Inc.', sector: 'Consumer Discretionary', subsector: 'Automobiles' },
  { ticker: 'ARM', name: 'Arm Holdings', sector: 'Technology', subsector: 'Semiconductors' },
  { ticker: 'SMCI', name: 'Super Micro Computer', sector: 'Technology', subsector: 'Technology Hardware' },
  { ticker: 'APP', name: 'AppLovin Corp.', sector: 'Technology', subsector: 'Software' },
  { ticker: 'CELH', name: 'Celsius Holdings', sector: 'Consumer Staples', subsector: 'Beverages' },
  { ticker: 'HIMS', name: 'Hims & Hers Health', sector: 'Healthcare', subsector: 'Health Care Services' },
  { ticker: 'RXRX', name: 'Recursion Pharmaceuticals', sector: 'Healthcare', subsector: 'Biotechnology' },
  { ticker: 'ROIV', name: 'Roivant Sciences', sector: 'Healthcare', subsector: 'Biotechnology' },
  { ticker: 'AXON', name: 'Axon Enterprise', sector: 'Industrials', subsector: 'Electronic Equipment' },
  { ticker: 'PODD', name: 'Insulet Corp.', sector: 'Healthcare', subsector: 'Health Care Equipment' },
  { ticker: 'TMDX', name: 'TransMedics Group', sector: 'Healthcare', subsector: 'Health Care Equipment' },
  { ticker: 'NTRA', name: 'Natera Inc.', sector: 'Healthcare', subsector: 'Health Care Equipment' },
  { ticker: 'RVTY', name: 'Revvity Inc.', sector: 'Healthcare', subsector: 'Life Sciences' },
  { ticker: 'INTU', name: 'Intuit Inc.', sector: 'Technology', subsector: 'Software' },
  { ticker: 'WDAY', name: 'Workday Inc.', sector: 'Technology', subsector: 'Software' },
  { ticker: 'TTD', name: 'Trade Desk Inc.', sector: 'Technology', subsector: 'Software' },
  { ticker: 'VEEV', name: 'Veeva Systems', sector: 'Technology', subsector: 'Software' },
  { ticker: 'HUBS', name: 'HubSpot Inc.', sector: 'Technology', subsector: 'Software' },
  { ticker: 'ZM', name: 'Zoom Video Communications', sector: 'Technology', subsector: 'Software' },
  { ticker: 'DOCU', name: 'DocuSign Inc.', sector: 'Technology', subsector: 'Software' },
  { ticker: 'BOX', name: 'Box Inc.', sector: 'Technology', subsector: 'Software' },
  { ticker: 'TWLO', name: 'Twilio Inc.', sector: 'Technology', subsector: 'Software' },
  { ticker: 'FIVN', name: 'Five9 Inc.', sector: 'Technology', subsector: 'Software' },
  { ticker: 'RNG', name: 'RingCentral Inc.', sector: 'Technology', subsector: 'Software' },
  { ticker: 'ESTC', name: 'Elastic N.V.', sector: 'Technology', subsector: 'Software' },
  { ticker: 'GTLB', name: 'GitLab Inc.', sector: 'Technology', subsector: 'Software' },
  { ticker: 'CFLT', name: 'Confluent Inc.', sector: 'Technology', subsector: 'Software' },
  { ticker: 'BILL', name: 'Bill.com Holdings', sector: 'Technology', subsector: 'Software' },
  { ticker: 'APPN', name: 'Appian Corp.', sector: 'Technology', subsector: 'Software' },
  { ticker: 'DT', name: 'Dynatrace Inc.', sector: 'Technology', subsector: 'Software' },
  { ticker: 'GLBE', name: 'Global-E Online', sector: 'Technology', subsector: 'Software' },
  { ticker: 'PCTY', name: 'Paylocity Holding', sector: 'Technology', subsector: 'Software' },
  { ticker: 'PAYC', name: 'Paycom Software', sector: 'Technology', subsector: 'Software' },
  { ticker: 'CSGP', name: 'CoStar Group', sector: 'Real Estate', subsector: 'Real Estate Services' },
  { ticker: 'Z', name: 'Zillow Group', sector: 'Real Estate', subsector: 'Real Estate Services' },
  { ticker: 'OPEN', name: 'Opendoor Technologies', sector: 'Real Estate', subsector: 'Real Estate Services' },
  { ticker: 'TREX', name: 'Trex Company', sector: 'Industrials', subsector: 'Building Products' },
  { ticker: 'WSO', name: 'Watsco Inc.', sector: 'Industrials', subsector: 'Building Products' },
  { ticker: 'GNRC', name: 'Generac Holdings', sector: 'Industrials', subsector: 'Electrical Components' },
  { ticker: 'TRMB', name: 'Trimble Inc.', sector: 'Technology', subsector: 'Electronic Equipment' },
  { ticker: 'LDOS', name: 'Leidos Holdings', sector: 'Industrials', subsector: 'IT Services' },
  { ticker: 'SAIC', name: 'Science Applications International', sector: 'Industrials', subsector: 'IT Services' },
  { ticker: 'BAH', name: 'Booz Allen Hamilton', sector: 'Industrials', subsector: 'Research & Consulting' },
  { ticker: 'DRS', name: 'Leonardo DRS', sector: 'Industrials', subsector: 'Aerospace & Defense' },
  { ticker: 'MSTR', name: 'MicroStrategy Inc.', sector: 'Technology', subsector: 'Software' },
  { ticker: 'LYRA', name: 'Lyra Therapeutics', sector: 'Healthcare', subsector: 'Biotechnology' },
  { ticker: 'WING', name: 'Wingstop Inc.', sector: 'Consumer Discretionary', subsector: 'Restaurants' },
  { ticker: 'TXRH', name: 'Texas Roadhouse', sector: 'Consumer Discretionary', subsector: 'Restaurants' },
  { ticker: 'DINO', name: 'HF Sinclair Corp.', sector: 'Energy', subsector: 'Oil & Gas Refining' },
  { ticker: 'TRGP', name: 'Targa Resources', sector: 'Energy', subsector: 'Oil & Gas Storage' },
  { ticker: 'OKE', name: 'ONEOK Inc.', sector: 'Energy', subsector: 'Oil & Gas Storage' },
  { ticker: 'AM', name: 'Antero Midstream', sector: 'Energy', subsector: 'Oil & Gas Storage' },
  { ticker: 'TW', name: 'Tradeweb Markets', sector: 'Financials', subsector: 'Financial Exchanges' },
  { ticker: 'MSCI', name: 'MSCI Inc.', sector: 'Financials', subsector: 'Financial Data & Analytics' },
  { ticker: 'FDS', name: 'FactSet Research Systems', sector: 'Financials', subsector: 'Financial Data & Analytics' },
  { ticker: 'BR', name: 'Broadridge Financial Solutions', sector: 'Technology', subsector: 'IT Services' },
  { ticker: 'WEX', name: 'WEX Inc.', sector: 'Financials', subsector: 'Data Processing' },
  { ticker: 'JKHY', name: 'Jack Henry & Associates', sector: 'Technology', subsector: 'IT Services' },
  { ticker: 'EPAM', name: 'EPAM Systems', sector: 'Technology', subsector: 'IT Services' },
  { ticker: 'GLOB', name: 'Globant S.A.', sector: 'Technology', subsector: 'IT Services' },
  { ticker: 'EXPO', name: 'Exponent Inc.', sector: 'Industrials', subsector: 'Research & Consulting' },
  { ticker: 'RHI', name: 'Robert Half International', sector: 'Industrials', subsector: 'Human Resources' },
  { ticker: 'MAN', name: 'ManpowerGroup Inc.', sector: 'Industrials', subsector: 'Human Resources' },
  { ticker: 'G', name: 'Genpact Ltd.', sector: 'Technology', subsector: 'IT Services' },
  { ticker: 'TASK', name: 'TaskUs Inc.', sector: 'Technology', subsector: 'IT Services' },
  { ticker: 'QTWO', name: 'Q2 Holdings', sector: 'Technology', subsector: 'Software' },
  { ticker: 'CACI', name: 'CACI International', sector: 'Industrials', subsector: 'IT Services' },
  { ticker: 'DLB', name: 'Dolby Laboratories', sector: 'Technology', subsector: 'Electronic Equipment' },
  { ticker: 'COHU', name: 'Cohu Inc.', sector: 'Technology', subsector: 'Semiconductor Equipment' },
  { ticker: 'ENTG', name: 'Entegris Inc.', sector: 'Technology', subsector: 'Semiconductor Equipment' },
  { ticker: 'UCTT', name: 'Ultra Clean Holdings', sector: 'Technology', subsector: 'Semiconductor Equipment' },
  { ticker: 'MKSI', name: 'MKS Instruments', sector: 'Technology', subsector: 'Semiconductor Equipment' },
  { ticker: 'TER', name: 'Teradyne Inc.', sector: 'Technology', subsector: 'Semiconductor Equipment' },
  { ticker: 'ACLS', name: 'Axcelis Technologies', sector: 'Technology', subsector: 'Semiconductor Equipment' },
  { ticker: 'WOLF', name: 'Wolfspeed Inc.', sector: 'Technology', subsector: 'Semiconductors' },
  { ticker: 'SITM', name: 'SiTime Corp.', sector: 'Technology', subsector: 'Semiconductors' },
  { ticker: 'ALGM', name: 'Allegro MicroSystems', sector: 'Technology', subsector: 'Semiconductors' },
  { ticker: 'CEVA', name: 'CEVA Inc.', sector: 'Technology', subsector: 'Semiconductors' },
  { ticker: 'LSCC', name: 'Lattice Semiconductor', sector: 'Technology', subsector: 'Semiconductors' },
  { ticker: 'AMBA', name: 'Ambarella Inc.', sector: 'Technology', subsector: 'Semiconductors' },
  { ticker: 'FORM', name: 'FormFactor Inc.', sector: 'Technology', subsector: 'Semiconductor Equipment' },
  { ticker: 'NXPI', name: 'NXP Semiconductors', sector: 'Technology', subsector: 'Semiconductors' },
  { ticker: 'STM', name: 'STMicroelectronics', sector: 'Technology', subsector: 'Semiconductors' },
  { ticker: 'MRVL', name: 'Marvell Technology', sector: 'Technology', subsector: 'Semiconductors' },
  { ticker: 'MTSI', name: 'MACOM Technology Solutions', sector: 'Technology', subsector: 'Semiconductors' },
  { ticker: 'ONTO', name: 'Onto Innovation', sector: 'Technology', subsector: 'Semiconductor Equipment' },
  { ticker: 'RMBS', name: 'Rambus Inc.', sector: 'Technology', subsector: 'Semiconductors' },
  { ticker: 'SMTC', name: 'Semtech Corp.', sector: 'Technology', subsector: 'Semiconductors' },
  { ticker: 'IIIV', name: 'i3 Verticals', sector: 'Technology', subsector: 'Software' },
  { ticker: 'PCVX', name: 'Vaxcyte Inc.', sector: 'Healthcare', subsector: 'Biotechnology' },
  { ticker: 'KRYS', name: 'Krystal Biotech', sector: 'Healthcare', subsector: 'Biotechnology' },
  { ticker: 'ARWR', name: 'Arrowhead Pharmaceuticals', sector: 'Healthcare', subsector: 'Biotechnology' },
  { ticker: 'ALNY', name: 'Alnylam Pharmaceuticals', sector: 'Healthcare', subsector: 'Biotechnology' },
  { ticker: 'INCY', name: 'Incyte Corp.', sector: 'Healthcare', subsector: 'Biotechnology' },
  { ticker: 'NVCR', name: 'NovoCure Ltd.', sector: 'Healthcare', subsector: 'Health Care Equipment' },
  { ticker: 'EXAS', name: 'Exact Sciences', sector: 'Healthcare', subsector: 'Health Care Equipment' },
  { ticker: 'NVAX', name: 'Novavax Inc.', sector: 'Healthcare', subsector: 'Biotechnology' },
  { ticker: 'BEAM', name: 'Beam Therapeutics', sector: 'Healthcare', subsector: 'Biotechnology' },
  { ticker: 'NTLA', name: 'Intellia Therapeutics', sector: 'Healthcare', subsector: 'Biotechnology' },
  { ticker: 'CRSP', name: 'CRISPR Therapeutics', sector: 'Healthcare', subsector: 'Biotechnology' },
  { ticker: 'EDIT', name: 'Editas Medicine', sector: 'Healthcare', subsector: 'Biotechnology' },
  { ticker: 'IONS', name: 'Ionis Pharmaceuticals', sector: 'Healthcare', subsector: 'Biotechnology' },
  { ticker: 'ACAD', name: 'ACADIA Pharmaceuticals', sector: 'Healthcare', subsector: 'Biotechnology' },
  { ticker: 'JAZZ', name: 'Jazz Pharmaceuticals', sector: 'Healthcare', subsector: 'Pharmaceuticals' },
  { ticker: 'RARE', name: 'Ultragenyx Pharmaceutical', sector: 'Healthcare', subsector: 'Biotechnology' },
  { ticker: 'SRRK', name: 'Scholar Rock', sector: 'Healthcare', subsector: 'Biotechnology' },
  { ticker: 'FOLD', name: 'Amicus Therapeutics', sector: 'Healthcare', subsector: 'Biotechnology' },
  { ticker: 'IMVT', name: 'Immunovant Inc.', sector: 'Healthcare', subsector: 'Biotechnology' },
  { ticker: 'RCUS', name: 'Arcus Biosciences', sector: 'Healthcare', subsector: 'Biotechnology' },
  { ticker: 'GOSS', name: 'Gossamer Bio', sector: 'Healthcare', subsector: 'Biotechnology' },
  { ticker: 'TGTX', name: 'TG Therapeutics', sector: 'Healthcare', subsector: 'Biotechnology' },
  { ticker: 'KYMR', name: 'Kymera Therapeutics', sector: 'Healthcare', subsector: 'Biotechnology' },
  { ticker: 'DNLI', name: 'Denali Therapeutics', sector: 'Healthcare', subsector: 'Biotechnology' },
  { ticker: 'PRAX', name: 'Praxis Precision Medicine', sector: 'Healthcare', subsector: 'Biotechnology' },
  { ticker: 'RIGL', name: 'Rigel Pharmaceuticals', sector: 'Healthcare', subsector: 'Biotechnology' },
  { ticker: 'MRUS', name: 'Merus N.V.', sector: 'Healthcare', subsector: 'Biotechnology' },
  { ticker: 'VKTX', name: 'Viking Therapeutics', sector: 'Healthcare', subsector: 'Biotechnology' },
  { ticker: 'PTCT', name: 'PTC Therapeutics', sector: 'Healthcare', subsector: 'Biotechnology' },
  { ticker: 'LRMR', name: 'Larimar Therapeutics', sector: 'Healthcare', subsector: 'Biotechnology' },
  { ticker: 'ARQT', name: 'Arcutis Biotherapeutics', sector: 'Healthcare', subsector: 'Biotechnology' },
  { ticker: 'DAWN', name: 'Day One Biopharmaceuticals', sector: 'Healthcare', subsector: 'Biotechnology' },
  { ticker: 'TARS', name: 'Tarsus Pharmaceuticals', sector: 'Healthcare', subsector: 'Pharmaceuticals' },
  { ticker: 'VERA', name: 'Vera Therapeutics', sector: 'Healthcare', subsector: 'Biotechnology' },
]

export const SP500_TICKERS = SP500_STOCKS.map(s => s.ticker)

export const SP500_BY_SECTOR = SP500_STOCKS.reduce((acc, stock) => {
  if (!acc[stock.sector]) acc[stock.sector] = []
  acc[stock.sector].push(stock)
  return acc
}, {})
